import {getTeacher} from '@/app/access-auth';
import {database} from '@/lib/storage';
import {providerState,saveConnection,connection} from '@/lib/provider-store';
import {providerConfigSchema,providerIds,providers} from '@/lib/providers';
import {generate} from '@/lib/provider-adapters';
import {z} from 'zod';
export const dynamic='force-dynamic';
const json=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(){const user=await getTeacher();if(!user)return json({error:'Sign in to manage connections.'},401);try{return json(await providerState(user.userId))}catch{return json({error:'Connection settings are temporarily unavailable. Please retry.'},503)}}
export async function POST(req:Request){const user=await getTeacher();if(!user)return json({error:'Sign in to manage connections.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Cross-site request rejected.'},403);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'JSON is required.'},415);try{const text=await req.text();if(text.length>10000)return json({error:'Connection settings are too large.'},413);const body=JSON.parse(text);const owner=user.userId;if(body.action==='save'){const config=providerConfigSchema.parse(body);const key=z.string().trim().max(600).optional().parse(body.key);if(key&&(!/^[\x21-\x7e]{10,600}$/.test(key)))throw new Error('Enter a valid API key.');await saveConnection(owner,config,key||undefined);return json({saved:true});}
if(body.action==='select'){const pref=z.object({writing:z.enum(['none',...providerIds]),speaking:z.enum(['none','openai','gemini','qwen'])}).parse(body);const s=await providerState(owner);for(const id of [pref.writing,pref.speaking])if(id!=='none'&&!s.connections.some(c=>c.provider===id&&c.configured))throw new Error('Save that provider connection first.');await database().prepare('INSERT INTO ai_preferences (owner,writing,speaking) VALUES (?,?,?) ON CONFLICT(owner) DO UPDATE SET writing=excluded.writing,speaking=excluded.speaking').bind(owner,pref.writing,pref.speaking).run();return json({saved:true});}
const id=z.enum(providerIds).parse(body.provider);if(body.action==='disconnect'){const s=await providerState(owner);await database().batch([database().prepare('DELETE FROM ai_connections WHERE owner = ? AND provider = ?').bind(owner,id),database().prepare('INSERT INTO ai_preferences (owner,writing,speaking) VALUES (?,?,?) ON CONFLICT(owner) DO UPDATE SET writing=excluded.writing,speaking=excluded.speaking').bind(owner,s.writing===id?'none':s.writing,s.speaking===id?'none':s.speaking)]);return json({disconnected:true});}
if(body.action==='test'){const c=await connection(owner,id);const prompt=[{type:'input_text' as const,text:'Connection test. Return only JSON {"ok":true}.'}];const result=await generate(c,prompt,'Respond in JSON only. No student data is included.',false,2048);if(result.ok!==true)throw new Error('The model responded, but not in the expected format. Check model compatibility.');if(providers[id].audio&&c.audioModel!==c.textModel){const ar=await generate(c,prompt,'Return JSON only.',true,2048);if(ar.ok!==true)throw new Error('The speaking model did not return the expected test response.');}await database().prepare('UPDATE ai_connections SET tested_at = ? WHERE owner = ? AND provider = ? AND config = ?').bind(new Date().toISOString(),owner,id,JSON.stringify(providerConfigSchema.parse(c))).run();return json({tested:true,message:'Key and model access verified. This test did not evaluate image/audio quality.'});}return json({error:'Unknown connection action.'},400);
}catch(e){if(e instanceof z.ZodError)return json({error:e.issues[0]?.message||'Check your connection settings.'},400);return json({error:e instanceof Error?e.message:'Could not update the connection. Please retry.'},400);}}
