import {Buffer} from 'node:buffer';
import type {ProviderConnection} from './providers';
export type Part={type:'input_text';text:string}|{type:'input_image';image_url:string}|{type:'input_file';filename:string;file_data:string}|{type:'input_audio';data:string;mime:string};
function dataUrl(value:string){const m=/^data:([^;]+);base64,([A-Za-z0-9+/=\r\n]+)$/.exec(value);if(!m)throw new Error('Invalid media content.');return {mime:m[1],data:m[2]};}
export function qwenEndpoint(c:ProviderConnection){if(!/^[a-zA-Z0-9-]{1,80}$/.test(c.workspace)||!['ap-southeast-1','cn-beijing'].includes(c.region))throw new Error('Check the Qwen workspace and region.');return `https://${c.workspace}.${c.region}.maas.aliyuncs.com/compatible-mode/v1/chat/completions`;}
export function truncated(audio:boolean):never{throw new Error(audio?'The model ran out of response space before it finished describing this recording. Use a shorter recording, or choose a speaking model with a larger response limit. Your saved submission is unchanged.':'The model ran out of response space before it finished. Try again, or shorten the submission. Your saved submission is unchanged.');}
// Speaking responses are free-form JSON: providers vary the transcript key, split it into examiner/candidate
// turns, or scatter the observations across sibling keys. Normalise instead of rejecting a usable answer.
const speechKeys=['transcript','transcription','candidate_transcript','candidateTranscript','candidate_speech','candidate','speech','utterance','text','content','dialogue','turns','segments','lines'];
const observationKeys=['observations','observation','analysis','evidence','notes'];
const speakerKeys=['speaker','role','who','part'];
export function flattenSpeech(value:unknown,depth=0):string{if(value==null)return '';if(typeof value==='string')return value.trim();if(typeof value==='number'||typeof value==='boolean')return String(value);if(depth>5)return '';if(Array.isArray(value))return value.map(v=>flattenSpeech(v,depth+1)).filter(Boolean).join('\n');if(typeof value!=='object')return '';const o=value as Record<string,unknown>;const speaker=speakerKeys.map(k=>o[k]).find(v=>typeof v==='string'&&v.trim()) as string|undefined;const key=speechKeys.find(k=>o[k]!==undefined);const body=key?flattenSpeech(o[key],depth+1):Object.entries(o).filter(([k])=>!speakerKeys.includes(k)).map(([k,v])=>{const t=flattenSpeech(v,depth+1);return t&&!/^\d+$/.test(k)?k+': '+t:t}).filter(Boolean).join('\n');return body&&speaker?speaker.trim()+': '+body:body;}
export function audioAnalysis(parsed:unknown){let root=parsed;for(let i=0;i<3;i++){if(!root||typeof root!=='object'||Array.isArray(root))break;const o=root as Record<string,unknown>;const keys=Object.keys(o);if(keys.some(k=>speechKeys.includes(k)||observationKeys.includes(k)))break;const only=keys.length===1?o[keys[0]]:undefined;if(!only||typeof only!=='object')break;root=only;}
const o=root&&typeof root==='object'&&!Array.isArray(root)?root as Record<string,unknown>:{};
const transcript=flattenSpeech(Array.isArray(root)?root:speechKeys.map(k=>o[k]).find(v=>v!=null&&v!=='')).slice(0,40000);
const named=observationKeys.map(k=>o[k]).find(v=>v!=null&&v!=='');const rest=Object.fromEntries(Object.entries(o).filter(([k])=>!speechKeys.includes(k)&&!observationKeys.includes(k)&&o[k]!=null&&o[k]!==''));
const observations=named!==undefined?(typeof named==='string'?named.trim().slice(0,40000):named):transcript&&Object.keys(rest).length?rest:'';
if(!transcript&&!observations)throw new Error('The speaking model returned no transcript or audio observations for this recording. Please retry; your saved submission is unchanged.');
return {transcript,observations};}
// Providers wrap their JSON in prose, and a verbatim transcript full of newlines and quotes routinely comes
// back with raw control characters inside the strings. Repair what is recoverable, and tell a response that
// simply stopped mid-answer apart from one that is malformed.
function scanJSON(text:string){let fixed='',inString=false,escaped=false,depth=0,end=-1;for(let i=0;i<text.length;i++){const ch=text[i];if(inString){if(escaped){escaped=false;fixed+=ch;continue;}if(ch==='\\'){escaped=true;fixed+=ch;continue;}if(ch==='"'){inString=false;fixed+=ch;continue;}if(text.charCodeAt(i)<0x20){fixed+=ch==='\n'?'\\n':ch==='\r'?'\\r':ch==='\t'?'\\t':'';continue;}fixed+=ch;continue;}if(ch==='"')inString=true;else if(ch==='{'||ch==='[')depth++;else if(ch==='}'||ch===']'){depth--;if(!depth&&end<0)end=i;}fixed+=ch;}return {fixed,end,incomplete:inString||depth>0};}
export function parseJSON(text:string,audio=false){const cleaned=text.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'').trim();const start=cleaned.search(/[{[]/);const body=start>0?cleaned.slice(start):cleaned;
const scan=scanJSON(body);const first=scan.end>=0?body.slice(0,scan.end+1):'';
for(const candidate of [cleaned,body,first,scanJSON(first).fixed,scan.fixed])if(candidate)try{return JSON.parse(candidate)}catch{/* try the next repair */}
if(scan.incomplete)truncated(audio);
throw new Error('The provider returned incomplete or invalid JSON. Your saved submission is unchanged.');}
export async function providerRequest(url:string,headers:Record<string,string>,body:unknown,fetcher:typeof fetch=fetch,now:()=>number=Date.now){const serialized=JSON.stringify(body);if(url.startsWith('https://generativelanguage.googleapis.com/')&&Buffer.byteLength(serialized)>19*1024*1024)throw new Error('These files are too large for Gemini inline processing. Use smaller images or an audio file under 12 MB.');
for(let attempt=0;;attempt++){const started=now();const r=await fetcher(url,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:serialized,redirect:'manual',signal:AbortSignal.timeout(110000)});if(r.ok)return r;await r.body?.cancel();
// A busy model answers in seconds; retry that once. A 5xx after a long wait is not worth sending the audio again.
if([500,502,503,504].includes(r.status)&&!attempt&&now()-started<20000){await new Promise(wait=>setTimeout(wait,2000));continue;}
if(r.status>=300&&r.status<400)throw new Error('The provider returned an unexpected redirect. The request was stopped to protect your API key.');if([401,403].includes(r.status))throw new Error('The provider rejected this API key or model access. Check the key, region and permissions.');if(r.status===429)throw new Error('The provider reached a quota or rate limit. Check API billing or try later.');if(r.status===404)throw new Error('The selected model or workspace was not found. Check the model ID and region.');if(r.status>=500)throw new Error('The provider is temporarily overloaded or unavailable (HTTP '+r.status+'). This is on their side, not your submission: wait a minute and try again, or pick another provider in AI connection. Your saved submission is unchanged.');throw new Error('The provider could not process this request (HTTP '+r.status+'). Check model compatibility and file limits.');}}
export async function readQwenStream(r:Response){if(!r.body)throw new Error('The provider returned no response.');const reader=r.body.getReader();const decoder=new TextDecoder();let pending='',output='',finished=false;try{while(true){const {done,value}=await reader.read();pending+=decoder.decode(value,{stream:!done});const lines=pending.split('\n');pending=lines.pop()||'';if(done&&pending){lines.push(pending);pending='';}for(const line of lines){if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(data==='[DONE]'){finished=true;continue;}if(!data)continue;let chunk;try{chunk=JSON.parse(data)}catch{throw new Error('The provider sent an invalid response stream.');}if(chunk.error)throw new Error('The provider stopped the response. Try again later.');output+=chunk.choices?.[0]?.delta?.content||'';if(chunk.choices?.[0]?.finish_reason==='stop')finished=true;if(output.length>150000)throw new Error('The provider response is too large.');}if(done)break;}}finally{await reader.cancel().catch(()=>{})}if(!finished)throw new Error('The provider response was interrupted. Please retry.');return output;}
export async function generate(c:ProviderConnection,parts:Part[],instruction:string,audio=false,maxTokens=6500,fetcher:typeof fetch=fetch){const model=audio?c.audioModel:c.textModel;let raw='';if(c.provider==='claude'&&audio)throw new Error('Claude cannot listen to audio in this integration. Choose Gemini, Qwen Omni or OpenAI for speaking.');
if(c.provider==='openai'){if(audio){const content=parts.map(p=>p.type==='input_audio'?{type:'input_audio',input_audio:{data:p.data,format:p.mime==='audio/mpeg'?'mp3':'wav'}}:p.type==='input_text'?{type:'text',text:p.text}:null).filter(Boolean);const r=await providerRequest('https://api.openai.com/v1/chat/completions',{Authorization:'Bearer '+c.key},{model,store:false,modalities:['text'],messages:[{role:'system',content:instruction},{role:'user',content}],max_completion_tokens:maxTokens},fetcher);const d:any=await r.json();if(d.choices?.[0]?.finish_reason==='length')truncated(audio);raw=d.choices?.[0]?.message?.content||'';}else{const r=await providerRequest('https://api.openai.com/v1/responses',{Authorization:'Bearer '+c.key},{model,store:false,instructions:instruction,input:[{role:'user',content:parts}],text:{format:{type:'json_object'}},max_output_tokens:maxTokens},fetcher);const d:any=await r.json();if(d.incomplete_details?.reason==='max_output_tokens')truncated(audio);raw=(d.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==='output_text').map((x:any)=>x.text).join('');}}
else if(c.provider==='gemini'){const content=parts.map(p=>{if(p.type==='input_text')return {text:p.text};const d=p.type==='input_audio'?{mime:p.mime,data:p.data}:dataUrl(p.type==='input_file'?p.file_data:p.image_url);return {inlineData:{mimeType:d.mime,data:d.data}}});const thinking=model.startsWith('gemini-2.5')?{thinkingConfig:{thinkingBudget:Math.max(512,Math.min(8192,Math.floor(maxTokens/3)))}}:{};const r=await providerRequest('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent',{'x-goog-api-key':c.key},{systemInstruction:{parts:[{text:instruction}]},contents:[{role:'user',parts:content}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:maxTokens,...thinking}},fetcher);const d:any=await r.json();const candidate=d.candidates?.[0];raw=(candidate?.content?.parts||[]).filter((p:any)=>p.text&&!p.thought).map((p:any)=>p.text).join('');if(d.promptFeedback?.blockReason||['SAFETY','PROHIBITED_CONTENT','RECITATION','BLOCKLIST'].includes(candidate?.finishReason))throw new Error('Gemini blocked this request under its own safety filters. Your saved submission is unchanged.');if(candidate?.finishReason==='MAX_TOKENS')truncated(audio);if(!raw.trim())throw new Error('Gemini returned an empty response. Please retry; your saved submission is unchanged.');}
else if(c.provider==='claude'){const content=parts.map(p=>{if(p.type==='input_text')return {type:'text',text:p.text};if(p.type==='input_audio')throw new Error('Claude audio input is unavailable.');const d=dataUrl(p.type==='input_file'?p.file_data:p.image_url);return {type:p.type==='input_file'?'document':'image',source:{type:'base64',media_type:d.mime,data:d.data}}});const r=await providerRequest('https://api.anthropic.com/v1/messages',{'x-api-key':c.key,'anthropic-version':'2023-06-01'},{model,system:instruction,max_tokens:maxTokens,messages:[{role:'user',content}]},fetcher);const d:any=await r.json();if(d.stop_reason==='max_tokens')truncated(audio);raw=(d.content||[]).filter((p:any)=>p.type==='text').map((p:any)=>p.text).join('');}
else{const content:any[]=[];for(const p of parts){if(p.type==='input_text')content.push({type:'text',text:p.text});else if(p.type==='input_file'){if(p.filename!=='official-ielts-band-descriptors.pdf')throw new Error('PDF pages must be converted to images before sending to Qwen. Refresh and try again.');const {extractText}=await import('unpdf');const d=dataUrl(p.file_data);const extracted=await extractText(new Uint8Array(Buffer.from(d.data,'base64')),{mergePages:true});if(extracted.text.length<500)throw new Error('The official rubric could not be read. Assessment stopped.');content.push({type:'text',text:'Official IELTS band descriptors (source PDF text):\n'+extracted.text});}else if(p.type==='input_image'){if(p.image_url.length>9.5*1024*1024)throw new Error('Qwen needs each encoded image below 10 MB. Use a smaller image.');content.push({type:'image_url',image_url:{url:p.image_url}});}else{if(p.data.length>9.5*1024*1024)throw new Error('Qwen needs an audio file below approximately 7 MB. Compress or shorten the recording.');content.push({type:'input_audio',input_audio:{data:'data:'+p.mime+';base64,'+p.data,format:p.mime==='audio/mpeg'?'mp3':'wav'}});}}const r=await providerRequest(qwenEndpoint(c),{Authorization:'Bearer '+c.key},{model,messages:[{role:'system',content:instruction},{role:'user',content}],stream:true,...(model.includes('omni')?{modalities:['text']}:{}),...(model.startsWith('qwen3-omni')?{enable_thinking:false}:{}),max_tokens:maxTokens},fetcher);raw=await readQwenStream(r);}
return parseJSON(raw,audio);}
