import {env} from 'cloudflare:workers';
import {database} from './storage';
import {providerIds,providers,ProviderId,ProviderConfig,ProviderConnection,ProviderState,AIAvailability,providerConfigSchema} from './providers';
import {sealKey,unsealKey} from './provider-crypto';
import {platformInfo,platformConnection} from './platform-ai';
import type {ProviderChoice} from './providers';
type Row={provider:ProviderId;config:string;encrypted_key:string;tested_at:string|null};
export async function providerState(owner:string,email:string):Promise<ProviderState>{const rows=await database().prepare('SELECT provider,config,encrypted_key,tested_at FROM ai_connections WHERE owner = ?').bind(owner).all<Row>();const prefs=await database().prepare('SELECT writing,speaking FROM ai_preferences WHERE owner = ?').bind(owner).first<{writing:ProviderChoice;speaking:ProviderChoice}>();const platform=platformInfo(env,email);const connections=providerIds.map(id=>{const row=rows.results.find(r=>r.provider===id);const fallback=id==='openai'&&!!env.OPENAI_API_KEY;return {...(row?JSON.parse(row.config):{provider:id,textModel:fallback?(env.OPENAI_TEXT_MODEL||providers[id].textModel):providers[id].textModel,audioModel:fallback?(env.OPENAI_AUDIO_MODEL||providers[id].audioModel):providers[id].audioModel,region:'ap-southeast-1',workspace:''}),configured:!!row||fallback,testedAt:row?.tested_at||null,source:row?'saved':fallback?'site':'none'};});// A saved Bandwise AI choice lapses if this teacher can no longer use it (e.g. removed from the test list).
// With nothing chosen yet, a teacher who may use Bandwise AI starts on it, so a new pilot teacher can mark straight away.
const choice=(c:ProviderChoice|undefined)=>c==='bandwise'&&!platform.available?'none':c||(platform.available?'bandwise':env.OPENAI_API_KEY?'openai':'none');return {connections,writing:choice(prefs?.writing),speaking:choice(prefs?.speaking),vaultReady:!!env.PROVIDER_ENCRYPTION_KEY,platform};}
// Bandwise AI runs on Gemini, so the page sees it as Gemini (for file limits and PDF handling) under its own name.
function side(s:ProviderState,choice:ProviderChoice){if(choice==='bandwise')return {ready:true,provider:'gemini' as const,name:s.platform.name};const c=s.connections.find(x=>x.provider===choice);return c?{ready:c.configured,provider:c.provider,name:providers[c.provider].name}:null;}
export function availability(s:ProviderState):AIAvailability {const w=side(s,s.writing);const a=side(s,s.speaking);return {writing:!!w?.ready,speaking:!!w?.ready&&!!a?.ready&&a.provider!=='claude',writingName:w?w.name:'No writing provider',speakingName:a?a.name:'No speaking provider',writingProvider:w?.provider??'none',speakingProvider:a?.provider??'none',writingPdf:w?providers[w.provider].pdf:false};}
export async function connection(owner:string,id:ProviderId):Promise<ProviderConnection>{const row=await database().prepare('SELECT provider,config,encrypted_key,tested_at FROM ai_connections WHERE owner = ? AND provider = ?').bind(owner,id).first<Row>();if(row){if(!env.PROVIDER_ENCRYPTION_KEY)throw new Error('Secure key storage is temporarily unavailable.');return {...providerConfigSchema.parse(JSON.parse(row.config)),key:await unsealKey(env.PROVIDER_ENCRYPTION_KEY,row.encrypted_key,owner+':'+id)};}if(id==='openai'&&env.OPENAI_API_KEY)return {provider:id,textModel:env.OPENAI_TEXT_MODEL||'gpt-4.1',audioModel:env.OPENAI_AUDIO_MODEL||'gpt-audio',region:'ap-southeast-1',workspace:'',key:env.OPENAI_API_KEY};throw new Error('Connect '+providers[id].name+' in Settings → AI connection first.');}
export async function selectedConnections(owner:string,email:string,speaking:boolean){const state=await providerState(owner,email);if(state.writing==='none')throw new Error('Choose a writing / feedback provider in Settings → AI connection.');const writing=state.writing==='bandwise'?platformConnection(env):await connection(owner,state.writing);let audio:ProviderConnection|undefined;if(speaking){if(state.speaking==='none'||state.speaking==='claude')throw new Error('Choose an audio-capable speaking provider in Settings → AI connection.');audio=state.speaking==='bandwise'?platformConnection(env):await connection(owner,state.speaking);}return {writing,audio};}
export async function saveConnection(owner:string,config:ProviderConfig,key?:string){if(!env.PROVIDER_ENCRYPTION_KEY)throw new Error('Secure key storage is temporarily unavailable.');const previous=key?null:await connection(owner,config.provider);const encrypted=await sealKey(env.PROVIDER_ENCRYPTION_KEY,key||previous!.key,owner+':'+config.provider);await database().prepare('INSERT INTO ai_connections (owner,provider,config,encrypted_key,tested_at) VALUES (?,?,?,?,NULL) ON CONFLICT(owner,provider) DO UPDATE SET config=excluded.config,encrypted_key=excluded.encrypted_key,tested_at=NULL').bind(owner,config.provider,JSON.stringify(config),encrypted).run();}
