import {sqliteTable,text,real,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const students=sqliteTable('students',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),target:real('target').notNull(),minBand:real('min_band'),email:text('email'),track:text('track').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_students_owner').on(t.owner)]);
export const assessments=sqliteTable('assessments',{id:text('id').primaryKey(),owner:text('owner').notNull(),studentId:text('student_id').notNull().references(()=>students.id),data:text('data').notNull(),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('idx_assessments_owner_student').on(t.owner,t.studentId)]);
export const aiConnections=sqliteTable('ai_connections',{owner:text('owner').notNull(),provider:text('provider').notNull(),config:text('config').notNull(),encryptedKey:text('encrypted_key').notNull(),testedAt:text('tested_at')},t=>[uniqueIndex('idx_ai_connections_owner_provider').on(t.owner,t.provider)]);
export const aiPreferences=sqliteTable('ai_preferences',{owner:text('owner').primaryKey(),writing:text('writing').notNull(),speaking:text('speaking').notNull()});
export const emailSettings=sqliteTable('email_settings',{owner:text('owner').primaryKey(),config:text('config').notNull(),encryptedPassword:text('encrypted_password').notNull(),testedAt:text('tested_at')});
// One row per AI provider call, for cost tracking. The assessment and task are kept even after the
// assessment is deleted, so past costs stay countable.
export const usageEvents=sqliteTable('usage_events',{id:text('id').primaryKey(),owner:text('owner').notNull(),assessmentId:text('assessment_id'),task:text('task'),action:text('action').notNull(),kind:text('kind').notNull(),provider:text('provider').notNull(),model:text('model').notNull(),inputTokens:integer('input_tokens').notNull(),audioTokens:integer('audio_tokens').notNull(),outputTokens:integer('output_tokens').notNull(),costUsd:real('cost_usd'),ok:integer('ok').notNull(),platform:integer('platform').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('idx_usage_events_owner_created').on(t.owner,t.createdAt)]);
// A teacher's branding for student reports (lib/branding.ts). The logo lives in R2 under branding/<logo_id>.
export const branding=sqliteTable('branding',{owner:text('owner').primaryKey(),name:text('name').notNull(),color:text('color').notNull(),contact:text('contact').notNull(),logoId:text('logo_id'),updatedAt:text('updated_at').notNull()});
